# Generated by Django 4.2.3 on 2023-08-17 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdminApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.TextField(max_length=15)),
                ('address', models.TextField()),
                ('landmark', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('country', models.TextField(max_length=255)),
                ('pincode', models.CharField(max_length=100)),
                ('payment_amount', models.FloatField(default=0)),
                ('payment_method', models.IntegerField(choices=[(1, 'COD (Cash On Delivery)'), (2, 'UPI ID(GPay,Paytm, etc'), (3, 'Credit / Debit Card'), (4, 'Net Banking')])),
                ('created_at', models.DateField(auto_now_add=True)),
                ('order_status', models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='processing', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('subtotal', models.FloatField()),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='UserApi.checkout')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApi.product')),
            ],
        ),
        migrations.CreateModel(
            name='CartList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApi.cartlist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApi.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
