# Generated by Django 4.2.3 on 2023-08-14 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApi', '0005_remove_product_quantity_product_stock'),
        ('UserApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='CartItems',
        ),
    ]
