# Generated by Django 4.2.3 on 2023-08-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApi', '0002_rename_items_cartitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartlist',
            name='order_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='processing', max_length=20),
        ),
    ]
