# Generated by Django 4.2.3 on 2023-08-16 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApi', '0005_ordereditem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderedItem',
        ),
    ]
