# Generated by Django 4.2.3 on 2023-08-16 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApi', '0006_delete_contact'),
        ('UserApi', '0006_delete_ordereditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('subtotal', models.FloatField()),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApi.checkout')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApi.product')),
            ],
        ),
    ]
