# Generated by Django 4.2.3 on 2023-08-16 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApi', '0007_ordereditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditem',
            name='checkout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='UserApi.checkout'),
        ),
    ]
