# Generated by Django 4.2.3 on 2023-08-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApi', '0006_delete_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.IntegerField(),
        ),
    ]
